---
engines:
  coverage:
    exclude_paths:
      - '**/types.ts'
exclude_paths:
  - '.storybook/**'
  - '.github/**'
  - '.*rc'
  - '.*rc.js'
  - '.*rc.json'
  - '.*.yml'
  - 'tsconfig.json'
  - '**/tsconfig.json'
  - 'package.json'
  - '**/package.json'
  - '**/__tests__/**'
  - '**.config.js'
  - '**.md'
  - 'init.js'
  - '**/index.ts'
